language: c

notifications:
  email: false

os:
  - linux

compiler:
  - gcc

env:
  global:
    - secure: "SoxDnL6a7OVhPX6hcjzwQjzW1+gGfJ0H36/BRzJvBKarZI4P9q2cArSpwWK4IGWLTWAzuKHb37uoZflY0xpbcwc0eiG6OtBiOTlL4Zbj6kc5XTbywAw/THRrRAE+6Y3xQ5UhygOFEffVj83cfDM9YuWobSO8Xx9mU6rraGCSVpk="
    - secure: "kZVvfKPjdoRzln1KMEglvgMFljd90YPtNDwQNpyu2aQ6zv6pkGUbtIni3kz8gDeirJ6eMQprbnH9n8olVh34bDIi+VC9wrneT58LQ83V6YFKicA34fHcUgXLiol7Cd5kDgEb/WuLXUnY3/p0znewmp98M2rZy5INAhE46vvdH0M="
    - secure: "Xz4TLsK/LCjMzIPjl2JHsROdjLAgwfJQhxxnvLAceF4NI0qU8MRTu/QObPzzU+TnqLBOqFJNwB5EDnTnbUyB9SiEFlOu1YkskVTkmQFA/KcZxNwww/U7O/ecUWfxsaaBgkwXh9fLXm4gJN/KLUZrzkjZGpUryjMqWJRFTL9JRyA="
    - COVERITY_SCAN_PROJECT_NAME=jgeboski/bitlbee-steam
    - COVERITY_SCAN_NOTIFICATION_EMAIL=nope
    - COVERITY_SCAN_BUILD_COMMAND=make
    - COVERITY_SCAN_BRANCH_PATTERN=coverity_scan

before_install:
  - echo "deb http://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_14.04 ./"
      | sudo tee /etc/apt/sources.list.d/suse.list
  - wget -O- "http://download.opensuse.org/repositories/openSUSE:/Tools/xUbuntu_14.04/Release.key"
      | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      --no-install-recommends
      asciidoc
      clang
      lynx
      osc
      xsltproc
      xmlto

install:
  - git clone https://github.com/bitlbee/bitlbee
  - cd bitlbee
  - ./configure
      --events=glib
      --ssl=gnutls
      --debug=1
      --plugins=1
      --jabber=0
      --msn=0
      --oscar=0
      --otr=0
      --purple=0
      --skype=0
      --twitter=0
      --yahoo=0
  - make
  - sudo make install install-dev
  - cd -
  - rm -rf bitlbee

script:
  - curl -s "https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh" | bash || true
  - ./travis.sh
